/*
 * AWS Amplify
 * Amplify enables developers to develop and deploy cloud-powered mobile and web apps. The Amplify Console provides a continuous delivery and hosting service for web applications. For more information, see the <a href=\"https://docs.aws.amazon.com/amplify/latest/userguide/welcome.html\">Amplify Console User Guide</a>. The Amplify Framework is a comprehensive set of SDKs, libraries, tools, and documentation for client app development. For more information, see the <a href=\"https://docs.amplify.aws/\">Amplify Framework.</a> 
 *
 * The version of the OpenAPI document: 2017-07-25
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.Map;
import org.openapitools.client.model.Stage;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AppAutoBranchCreationConfig
 */
public class AppAutoBranchCreationConfigTest {
    private final AppAutoBranchCreationConfig model = new AppAutoBranchCreationConfig();

    /**
     * Model tests for AppAutoBranchCreationConfig
     */
    @Test
    public void testAppAutoBranchCreationConfig() {
        // TODO: test AppAutoBranchCreationConfig
    }

    /**
     * Test the property 'stage'
     */
    @Test
    public void stageTest() {
        // TODO: test stage
    }

    /**
     * Test the property 'framework'
     */
    @Test
    public void frameworkTest() {
        // TODO: test framework
    }

    /**
     * Test the property 'enableAutoBuild'
     */
    @Test
    public void enableAutoBuildTest() {
        // TODO: test enableAutoBuild
    }

    /**
     * Test the property 'environmentVariables'
     */
    @Test
    public void environmentVariablesTest() {
        // TODO: test environmentVariables
    }

    /**
     * Test the property 'basicAuthCredentials'
     */
    @Test
    public void basicAuthCredentialsTest() {
        // TODO: test basicAuthCredentials
    }

    /**
     * Test the property 'enableBasicAuth'
     */
    @Test
    public void enableBasicAuthTest() {
        // TODO: test enableBasicAuth
    }

    /**
     * Test the property 'enablePerformanceMode'
     */
    @Test
    public void enablePerformanceModeTest() {
        // TODO: test enablePerformanceMode
    }

    /**
     * Test the property 'buildSpec'
     */
    @Test
    public void buildSpecTest() {
        // TODO: test buildSpec
    }

    /**
     * Test the property 'enablePullRequestPreview'
     */
    @Test
    public void enablePullRequestPreviewTest() {
        // TODO: test enablePullRequestPreview
    }

    /**
     * Test the property 'pullRequestEnvironmentName'
     */
    @Test
    public void pullRequestEnvironmentNameTest() {
        // TODO: test pullRequestEnvironmentName
    }

}
