/*
 * AWS Amplify
 * Amplify enables developers to develop and deploy cloud-powered mobile and web apps. The Amplify Console provides a continuous delivery and hosting service for web applications. For more information, see the <a href=\"https://docs.aws.amazon.com/amplify/latest/userguide/welcome.html\">Amplify Console User Guide</a>. The Amplify Framework is a comprehensive set of SDKs, libraries, tools, and documentation for client app development. For more information, see the <a href=\"https://docs.amplify.aws/\">Amplify Framework.</a> 
 *
 * The version of the OpenAPI document: 2017-07-25
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateBackendEnvironmentRequest
 */
public class CreateBackendEnvironmentRequestTest {
    private final CreateBackendEnvironmentRequest model = new CreateBackendEnvironmentRequest();

    /**
     * Model tests for CreateBackendEnvironmentRequest
     */
    @Test
    public void testCreateBackendEnvironmentRequest() {
        // TODO: test CreateBackendEnvironmentRequest
    }

    /**
     * Test the property 'environmentName'
     */
    @Test
    public void environmentNameTest() {
        // TODO: test environmentName
    }

    /**
     * Test the property 'stackName'
     */
    @Test
    public void stackNameTest() {
        // TODO: test stackName
    }

    /**
     * Test the property 'deploymentArtifacts'
     */
    @Test
    public void deploymentArtifactsTest() {
        // TODO: test deploymentArtifacts
    }

}
