/*
 * AWS Amplify
 * Amplify enables developers to develop and deploy cloud-powered mobile and web apps. The Amplify Console provides a continuous delivery and hosting service for web applications. For more information, see the <a href=\"https://docs.aws.amazon.com/amplify/latest/userguide/welcome.html\">Amplify Console User Guide</a>. The Amplify Framework is a comprehensive set of SDKs, libraries, tools, and documentation for client app development. For more information, see the <a href=\"https://docs.amplify.aws/\">Amplify Framework.</a> 
 *
 * The version of the OpenAPI document: 2017-07-25
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.Stage;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateBranchResultBranch
 */
public class CreateBranchResultBranchTest {
    private final CreateBranchResultBranch model = new CreateBranchResultBranch();

    /**
     * Model tests for CreateBranchResultBranch
     */
    @Test
    public void testCreateBranchResultBranch() {
        // TODO: test CreateBranchResultBranch
    }

    /**
     * Test the property 'branchArn'
     */
    @Test
    public void branchArnTest() {
        // TODO: test branchArn
    }

    /**
     * Test the property 'branchName'
     */
    @Test
    public void branchNameTest() {
        // TODO: test branchName
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'stage'
     */
    @Test
    public void stageTest() {
        // TODO: test stage
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'enableNotification'
     */
    @Test
    public void enableNotificationTest() {
        // TODO: test enableNotification
    }

    /**
     * Test the property 'createTime'
     */
    @Test
    public void createTimeTest() {
        // TODO: test createTime
    }

    /**
     * Test the property 'updateTime'
     */
    @Test
    public void updateTimeTest() {
        // TODO: test updateTime
    }

    /**
     * Test the property 'environmentVariables'
     */
    @Test
    public void environmentVariablesTest() {
        // TODO: test environmentVariables
    }

    /**
     * Test the property 'enableAutoBuild'
     */
    @Test
    public void enableAutoBuildTest() {
        // TODO: test enableAutoBuild
    }

    /**
     * Test the property 'customDomains'
     */
    @Test
    public void customDomainsTest() {
        // TODO: test customDomains
    }

    /**
     * Test the property 'framework'
     */
    @Test
    public void frameworkTest() {
        // TODO: test framework
    }

    /**
     * Test the property 'activeJobId'
     */
    @Test
    public void activeJobIdTest() {
        // TODO: test activeJobId
    }

    /**
     * Test the property 'totalNumberOfJobs'
     */
    @Test
    public void totalNumberOfJobsTest() {
        // TODO: test totalNumberOfJobs
    }

    /**
     * Test the property 'enableBasicAuth'
     */
    @Test
    public void enableBasicAuthTest() {
        // TODO: test enableBasicAuth
    }

    /**
     * Test the property 'enablePerformanceMode'
     */
    @Test
    public void enablePerformanceModeTest() {
        // TODO: test enablePerformanceMode
    }

    /**
     * Test the property 'thumbnailUrl'
     */
    @Test
    public void thumbnailUrlTest() {
        // TODO: test thumbnailUrl
    }

    /**
     * Test the property 'basicAuthCredentials'
     */
    @Test
    public void basicAuthCredentialsTest() {
        // TODO: test basicAuthCredentials
    }

    /**
     * Test the property 'buildSpec'
     */
    @Test
    public void buildSpecTest() {
        // TODO: test buildSpec
    }

    /**
     * Test the property 'ttl'
     */
    @Test
    public void ttlTest() {
        // TODO: test ttl
    }

    /**
     * Test the property 'associatedResources'
     */
    @Test
    public void associatedResourcesTest() {
        // TODO: test associatedResources
    }

    /**
     * Test the property 'enablePullRequestPreview'
     */
    @Test
    public void enablePullRequestPreviewTest() {
        // TODO: test enablePullRequestPreview
    }

    /**
     * Test the property 'pullRequestEnvironmentName'
     */
    @Test
    public void pullRequestEnvironmentNameTest() {
        // TODO: test pullRequestEnvironmentName
    }

    /**
     * Test the property 'destinationBranch'
     */
    @Test
    public void destinationBranchTest() {
        // TODO: test destinationBranch
    }

    /**
     * Test the property 'sourceBranch'
     */
    @Test
    public void sourceBranchTest() {
        // TODO: test sourceBranch
    }

    /**
     * Test the property 'backendEnvironmentArn'
     */
    @Test
    public void backendEnvironmentArnTest() {
        // TODO: test backendEnvironmentArn
    }

}
