/*
 * AWS Amplify
 * Amplify enables developers to develop and deploy cloud-powered mobile and web apps. The Amplify Console provides a continuous delivery and hosting service for web applications. For more information, see the <a href=\"https://docs.aws.amazon.com/amplify/latest/userguide/welcome.html\">Amplify Console User Guide</a>. The Amplify Framework is a comprehensive set of SDKs, libraries, tools, and documentation for client app development. For more information, see the <a href=\"https://docs.amplify.aws/\">Amplify Framework.</a> 
 *
 * The version of the OpenAPI document: 2017-07-25
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.DomainStatus;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DomainAssociation
 */
public class DomainAssociationTest {
    private final DomainAssociation model = new DomainAssociation();

    /**
     * Model tests for DomainAssociation
     */
    @Test
    public void testDomainAssociation() {
        // TODO: test DomainAssociation
    }

    /**
     * Test the property 'domainAssociationArn'
     */
    @Test
    public void domainAssociationArnTest() {
        // TODO: test domainAssociationArn
    }

    /**
     * Test the property 'domainName'
     */
    @Test
    public void domainNameTest() {
        // TODO: test domainName
    }

    /**
     * Test the property 'enableAutoSubDomain'
     */
    @Test
    public void enableAutoSubDomainTest() {
        // TODO: test enableAutoSubDomain
    }

    /**
     * Test the property 'autoSubDomainCreationPatterns'
     */
    @Test
    public void autoSubDomainCreationPatternsTest() {
        // TODO: test autoSubDomainCreationPatterns
    }

    /**
     * Test the property 'autoSubDomainIAMRole'
     */
    @Test
    public void autoSubDomainIAMRoleTest() {
        // TODO: test autoSubDomainIAMRole
    }

    /**
     * Test the property 'domainStatus'
     */
    @Test
    public void domainStatusTest() {
        // TODO: test domainStatus
    }

    /**
     * Test the property 'statusReason'
     */
    @Test
    public void statusReasonTest() {
        // TODO: test statusReason
    }

    /**
     * Test the property 'certificateVerificationDNSRecord'
     */
    @Test
    public void certificateVerificationDNSRecordTest() {
        // TODO: test certificateVerificationDNSRecord
    }

    /**
     * Test the property 'subDomains'
     */
    @Test
    public void subDomainsTest() {
        // TODO: test subDomains
    }

}
