/*
 * AWS Amplify
 * Amplify enables developers to develop and deploy cloud-powered mobile and web apps. The Amplify Console provides a continuous delivery and hosting service for web applications. For more information, see the <a href=\"https://docs.aws.amazon.com/amplify/latest/userguide/welcome.html\">Amplify Console User Guide</a>. The Amplify Framework is a comprehensive set of SDKs, libraries, tools, and documentation for client app development. For more information, see the <a href=\"https://docs.amplify.aws/\">Amplify Framework.</a> 
 *
 * The version of the OpenAPI document: 2017-07-25
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.client.model.JobStatus;
import org.openapitools.client.model.JobType;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for StartDeploymentResultJobSummary
 */
public class StartDeploymentResultJobSummaryTest {
    private final StartDeploymentResultJobSummary model = new StartDeploymentResultJobSummary();

    /**
     * Model tests for StartDeploymentResultJobSummary
     */
    @Test
    public void testStartDeploymentResultJobSummary() {
        // TODO: test StartDeploymentResultJobSummary
    }

    /**
     * Test the property 'jobArn'
     */
    @Test
    public void jobArnTest() {
        // TODO: test jobArn
    }

    /**
     * Test the property 'jobId'
     */
    @Test
    public void jobIdTest() {
        // TODO: test jobId
    }

    /**
     * Test the property 'commitId'
     */
    @Test
    public void commitIdTest() {
        // TODO: test commitId
    }

    /**
     * Test the property 'commitMessage'
     */
    @Test
    public void commitMessageTest() {
        // TODO: test commitMessage
    }

    /**
     * Test the property 'commitTime'
     */
    @Test
    public void commitTimeTest() {
        // TODO: test commitTime
    }

    /**
     * Test the property 'startTime'
     */
    @Test
    public void startTimeTest() {
        // TODO: test startTime
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'endTime'
     */
    @Test
    public void endTimeTest() {
        // TODO: test endTime
    }

    /**
     * Test the property 'jobType'
     */
    @Test
    public void jobTypeTest() {
        // TODO: test jobType
    }

}
