/*
 * AWS Amplify
 * Amplify enables developers to develop and deploy cloud-powered mobile and web apps. The Amplify Console provides a continuous delivery and hosting service for web applications. For more information, see the <a href=\"https://docs.aws.amazon.com/amplify/latest/userguide/welcome.html\">Amplify Console User Guide</a>. The Amplify Framework is a comprehensive set of SDKs, libraries, tools, and documentation for client app development. For more information, see the <a href=\"https://docs.amplify.aws/\">Amplify Framework.</a> 
 *
 * The version of the OpenAPI document: 2017-07-25
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Map;
import org.openapitools.client.model.JobStatus;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Step
 */
public class StepTest {
    private final Step model = new Step();

    /**
     * Model tests for Step
     */
    @Test
    public void testStep() {
        // TODO: test Step
    }

    /**
     * Test the property 'stepName'
     */
    @Test
    public void stepNameTest() {
        // TODO: test stepName
    }

    /**
     * Test the property 'startTime'
     */
    @Test
    public void startTimeTest() {
        // TODO: test startTime
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'endTime'
     */
    @Test
    public void endTimeTest() {
        // TODO: test endTime
    }

    /**
     * Test the property 'logUrl'
     */
    @Test
    public void logUrlTest() {
        // TODO: test logUrl
    }

    /**
     * Test the property 'artifactsUrl'
     */
    @Test
    public void artifactsUrlTest() {
        // TODO: test artifactsUrl
    }

    /**
     * Test the property 'testArtifactsUrl'
     */
    @Test
    public void testArtifactsUrlTest() {
        // TODO: test testArtifactsUrl
    }

    /**
     * Test the property 'testConfigUrl'
     */
    @Test
    public void testConfigUrlTest() {
        // TODO: test testConfigUrl
    }

    /**
     * Test the property 'screenshots'
     */
    @Test
    public void screenshotsTest() {
        // TODO: test screenshots
    }

    /**
     * Test the property 'statusReason'
     */
    @Test
    public void statusReasonTest() {
        // TODO: test statusReason
    }

    /**
     * Test the property 'context'
     */
    @Test
    public void contextTest() {
        // TODO: test context
    }

}
