/*
 * AWS Amplify
 * Amplify enables developers to develop and deploy cloud-powered mobile and web apps. The Amplify Console provides a continuous delivery and hosting service for web applications. For more information, see the <a href=\"https://docs.aws.amazon.com/amplify/latest/userguide/welcome.html\">Amplify Console User Guide</a>. The Amplify Framework is a comprehensive set of SDKs, libraries, tools, and documentation for client app development. For more information, see the <a href=\"https://docs.amplify.aws/\">Amplify Framework.</a> 
 *
 * The version of the OpenAPI document: 2017-07-25
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.AppAutoBranchCreationConfig;
import org.openapitools.client.model.AppProductionBranch;
import org.openapitools.client.model.Platform;
import org.openapitools.client.model.RepositoryCloneMethod;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UpdateAppResultApp
 */
public class UpdateAppResultAppTest {
    private final UpdateAppResultApp model = new UpdateAppResultApp();

    /**
     * Model tests for UpdateAppResultApp
     */
    @Test
    public void testUpdateAppResultApp() {
        // TODO: test UpdateAppResultApp
    }

    /**
     * Test the property 'appId'
     */
    @Test
    public void appIdTest() {
        // TODO: test appId
    }

    /**
     * Test the property 'appArn'
     */
    @Test
    public void appArnTest() {
        // TODO: test appArn
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'repository'
     */
    @Test
    public void repositoryTest() {
        // TODO: test repository
    }

    /**
     * Test the property 'platform'
     */
    @Test
    public void platformTest() {
        // TODO: test platform
    }

    /**
     * Test the property 'createTime'
     */
    @Test
    public void createTimeTest() {
        // TODO: test createTime
    }

    /**
     * Test the property 'updateTime'
     */
    @Test
    public void updateTimeTest() {
        // TODO: test updateTime
    }

    /**
     * Test the property 'iamServiceRoleArn'
     */
    @Test
    public void iamServiceRoleArnTest() {
        // TODO: test iamServiceRoleArn
    }

    /**
     * Test the property 'environmentVariables'
     */
    @Test
    public void environmentVariablesTest() {
        // TODO: test environmentVariables
    }

    /**
     * Test the property 'defaultDomain'
     */
    @Test
    public void defaultDomainTest() {
        // TODO: test defaultDomain
    }

    /**
     * Test the property 'enableBranchAutoBuild'
     */
    @Test
    public void enableBranchAutoBuildTest() {
        // TODO: test enableBranchAutoBuild
    }

    /**
     * Test the property 'enableBranchAutoDeletion'
     */
    @Test
    public void enableBranchAutoDeletionTest() {
        // TODO: test enableBranchAutoDeletion
    }

    /**
     * Test the property 'enableBasicAuth'
     */
    @Test
    public void enableBasicAuthTest() {
        // TODO: test enableBasicAuth
    }

    /**
     * Test the property 'basicAuthCredentials'
     */
    @Test
    public void basicAuthCredentialsTest() {
        // TODO: test basicAuthCredentials
    }

    /**
     * Test the property 'customRules'
     */
    @Test
    public void customRulesTest() {
        // TODO: test customRules
    }

    /**
     * Test the property 'productionBranch'
     */
    @Test
    public void productionBranchTest() {
        // TODO: test productionBranch
    }

    /**
     * Test the property 'buildSpec'
     */
    @Test
    public void buildSpecTest() {
        // TODO: test buildSpec
    }

    /**
     * Test the property 'customHeaders'
     */
    @Test
    public void customHeadersTest() {
        // TODO: test customHeaders
    }

    /**
     * Test the property 'enableAutoBranchCreation'
     */
    @Test
    public void enableAutoBranchCreationTest() {
        // TODO: test enableAutoBranchCreation
    }

    /**
     * Test the property 'autoBranchCreationPatterns'
     */
    @Test
    public void autoBranchCreationPatternsTest() {
        // TODO: test autoBranchCreationPatterns
    }

    /**
     * Test the property 'autoBranchCreationConfig'
     */
    @Test
    public void autoBranchCreationConfigTest() {
        // TODO: test autoBranchCreationConfig
    }

    /**
     * Test the property 'repositoryCloneMethod'
     */
    @Test
    public void repositoryCloneMethodTest() {
        // TODO: test repositoryCloneMethod
    }

}
