/*
 * AWS Amplify
 * Amplify enables developers to develop and deploy cloud-powered mobile and web apps. The Amplify Console provides a continuous delivery and hosting service for web applications. For more information, see the <a href=\"https://docs.aws.amazon.com/amplify/latest/userguide/welcome.html\">Amplify Console User Guide</a>. The Amplify Framework is a comprehensive set of SDKs, libraries, tools, and documentation for client app development. For more information, see the <a href=\"https://docs.amplify.aws/\">Amplify Framework.</a> 
 *
 * The version of the OpenAPI document: 2017-07-25
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.AppAutoBranchCreationConfig;
import org.openapitools.client.model.AppProductionBranch;
import org.openapitools.client.model.Platform;
import org.openapitools.client.model.RepositoryCloneMethod;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 *  Represents the different branches of a repository for building, deploying, and hosting an Amplify app. 
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:08:57.241962+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class App {
  public static final String SERIALIZED_NAME_APP_ID = "appId";
  @SerializedName(SERIALIZED_NAME_APP_ID)
  @javax.annotation.Nonnull
  private String appId;

  public static final String SERIALIZED_NAME_APP_ARN = "appArn";
  @SerializedName(SERIALIZED_NAME_APP_ARN)
  @javax.annotation.Nonnull
  private String appArn;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  @javax.annotation.Nullable
  private Map tags;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nonnull
  private String description;

  public static final String SERIALIZED_NAME_REPOSITORY = "repository";
  @SerializedName(SERIALIZED_NAME_REPOSITORY)
  @javax.annotation.Nonnull
  private String repository;

  public static final String SERIALIZED_NAME_PLATFORM = "platform";
  @SerializedName(SERIALIZED_NAME_PLATFORM)
  @javax.annotation.Nonnull
  private Platform platform;

  public static final String SERIALIZED_NAME_CREATE_TIME = "createTime";
  @SerializedName(SERIALIZED_NAME_CREATE_TIME)
  @javax.annotation.Nonnull
  private OffsetDateTime createTime;

  public static final String SERIALIZED_NAME_UPDATE_TIME = "updateTime";
  @SerializedName(SERIALIZED_NAME_UPDATE_TIME)
  @javax.annotation.Nonnull
  private OffsetDateTime updateTime;

  public static final String SERIALIZED_NAME_IAM_SERVICE_ROLE_ARN = "iamServiceRoleArn";
  @SerializedName(SERIALIZED_NAME_IAM_SERVICE_ROLE_ARN)
  @javax.annotation.Nullable
  private String iamServiceRoleArn;

  public static final String SERIALIZED_NAME_ENVIRONMENT_VARIABLES = "environmentVariables";
  @SerializedName(SERIALIZED_NAME_ENVIRONMENT_VARIABLES)
  @javax.annotation.Nonnull
  private Map environmentVariables;

  public static final String SERIALIZED_NAME_DEFAULT_DOMAIN = "defaultDomain";
  @SerializedName(SERIALIZED_NAME_DEFAULT_DOMAIN)
  @javax.annotation.Nonnull
  private String defaultDomain;

  public static final String SERIALIZED_NAME_ENABLE_BRANCH_AUTO_BUILD = "enableBranchAutoBuild";
  @SerializedName(SERIALIZED_NAME_ENABLE_BRANCH_AUTO_BUILD)
  @javax.annotation.Nonnull
  private Boolean enableBranchAutoBuild;

  public static final String SERIALIZED_NAME_ENABLE_BRANCH_AUTO_DELETION = "enableBranchAutoDeletion";
  @SerializedName(SERIALIZED_NAME_ENABLE_BRANCH_AUTO_DELETION)
  @javax.annotation.Nullable
  private Boolean enableBranchAutoDeletion;

  public static final String SERIALIZED_NAME_ENABLE_BASIC_AUTH = "enableBasicAuth";
  @SerializedName(SERIALIZED_NAME_ENABLE_BASIC_AUTH)
  @javax.annotation.Nonnull
  private Boolean enableBasicAuth;

  public static final String SERIALIZED_NAME_BASIC_AUTH_CREDENTIALS = "basicAuthCredentials";
  @SerializedName(SERIALIZED_NAME_BASIC_AUTH_CREDENTIALS)
  @javax.annotation.Nullable
  private String basicAuthCredentials;

  public static final String SERIALIZED_NAME_CUSTOM_RULES = "customRules";
  @SerializedName(SERIALIZED_NAME_CUSTOM_RULES)
  @javax.annotation.Nullable
  private List customRules;

  public static final String SERIALIZED_NAME_PRODUCTION_BRANCH = "productionBranch";
  @SerializedName(SERIALIZED_NAME_PRODUCTION_BRANCH)
  @javax.annotation.Nullable
  private AppProductionBranch productionBranch;

  public static final String SERIALIZED_NAME_BUILD_SPEC = "buildSpec";
  @SerializedName(SERIALIZED_NAME_BUILD_SPEC)
  @javax.annotation.Nullable
  private String buildSpec;

  public static final String SERIALIZED_NAME_CUSTOM_HEADERS = "customHeaders";
  @SerializedName(SERIALIZED_NAME_CUSTOM_HEADERS)
  @javax.annotation.Nullable
  private String customHeaders;

  public static final String SERIALIZED_NAME_ENABLE_AUTO_BRANCH_CREATION = "enableAutoBranchCreation";
  @SerializedName(SERIALIZED_NAME_ENABLE_AUTO_BRANCH_CREATION)
  @javax.annotation.Nullable
  private Boolean enableAutoBranchCreation;

  public static final String SERIALIZED_NAME_AUTO_BRANCH_CREATION_PATTERNS = "autoBranchCreationPatterns";
  @SerializedName(SERIALIZED_NAME_AUTO_BRANCH_CREATION_PATTERNS)
  @javax.annotation.Nullable
  private List autoBranchCreationPatterns;

  public static final String SERIALIZED_NAME_AUTO_BRANCH_CREATION_CONFIG = "autoBranchCreationConfig";
  @SerializedName(SERIALIZED_NAME_AUTO_BRANCH_CREATION_CONFIG)
  @javax.annotation.Nullable
  private AppAutoBranchCreationConfig autoBranchCreationConfig;

  public static final String SERIALIZED_NAME_REPOSITORY_CLONE_METHOD = "repositoryCloneMethod";
  @SerializedName(SERIALIZED_NAME_REPOSITORY_CLONE_METHOD)
  @javax.annotation.Nullable
  private RepositoryCloneMethod repositoryCloneMethod;

  public App() {
  }

  public App appId(@javax.annotation.Nonnull String appId) {
    this.appId = appId;
    return this;
  }

  /**
   * Get appId
   * @return appId
   */
  @javax.annotation.Nonnull
  public String getAppId() {
    return appId;
  }

  public void setAppId(@javax.annotation.Nonnull String appId) {
    this.appId = appId;
  }


  public App appArn(@javax.annotation.Nonnull String appArn) {
    this.appArn = appArn;
    return this;
  }

  /**
   * Get appArn
   * @return appArn
   */
  @javax.annotation.Nonnull
  public String getAppArn() {
    return appArn;
  }

  public void setAppArn(@javax.annotation.Nonnull String appArn) {
    this.appArn = appArn;
  }


  public App name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public App tags(@javax.annotation.Nullable Map tags) {
    this.tags = tags;
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @javax.annotation.Nullable
  public Map getTags() {
    return tags;
  }

  public void setTags(@javax.annotation.Nullable Map tags) {
    this.tags = tags;
  }


  public App description(@javax.annotation.Nonnull String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nonnull
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nonnull String description) {
    this.description = description;
  }


  public App repository(@javax.annotation.Nonnull String repository) {
    this.repository = repository;
    return this;
  }

  /**
   * Get repository
   * @return repository
   */
  @javax.annotation.Nonnull
  public String getRepository() {
    return repository;
  }

  public void setRepository(@javax.annotation.Nonnull String repository) {
    this.repository = repository;
  }


  public App platform(@javax.annotation.Nonnull Platform platform) {
    this.platform = platform;
    return this;
  }

  /**
   * Get platform
   * @return platform
   */
  @javax.annotation.Nonnull
  public Platform getPlatform() {
    return platform;
  }

  public void setPlatform(@javax.annotation.Nonnull Platform platform) {
    this.platform = platform;
  }


  public App createTime(@javax.annotation.Nonnull OffsetDateTime createTime) {
    this.createTime = createTime;
    return this;
  }

  /**
   * Get createTime
   * @return createTime
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getCreateTime() {
    return createTime;
  }

  public void setCreateTime(@javax.annotation.Nonnull OffsetDateTime createTime) {
    this.createTime = createTime;
  }


  public App updateTime(@javax.annotation.Nonnull OffsetDateTime updateTime) {
    this.updateTime = updateTime;
    return this;
  }

  /**
   * Get updateTime
   * @return updateTime
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getUpdateTime() {
    return updateTime;
  }

  public void setUpdateTime(@javax.annotation.Nonnull OffsetDateTime updateTime) {
    this.updateTime = updateTime;
  }


  public App iamServiceRoleArn(@javax.annotation.Nullable String iamServiceRoleArn) {
    this.iamServiceRoleArn = iamServiceRoleArn;
    return this;
  }

  /**
   * Get iamServiceRoleArn
   * @return iamServiceRoleArn
   */
  @javax.annotation.Nullable
  public String getIamServiceRoleArn() {
    return iamServiceRoleArn;
  }

  public void setIamServiceRoleArn(@javax.annotation.Nullable String iamServiceRoleArn) {
    this.iamServiceRoleArn = iamServiceRoleArn;
  }


  public App environmentVariables(@javax.annotation.Nonnull Map environmentVariables) {
    this.environmentVariables = environmentVariables;
    return this;
  }

  /**
   * Get environmentVariables
   * @return environmentVariables
   */
  @javax.annotation.Nonnull
  public Map getEnvironmentVariables() {
    return environmentVariables;
  }

  public void setEnvironmentVariables(@javax.annotation.Nonnull Map environmentVariables) {
    this.environmentVariables = environmentVariables;
  }


  public App defaultDomain(@javax.annotation.Nonnull String defaultDomain) {
    this.defaultDomain = defaultDomain;
    return this;
  }

  /**
   * Get defaultDomain
   * @return defaultDomain
   */
  @javax.annotation.Nonnull
  public String getDefaultDomain() {
    return defaultDomain;
  }

  public void setDefaultDomain(@javax.annotation.Nonnull String defaultDomain) {
    this.defaultDomain = defaultDomain;
  }


  public App enableBranchAutoBuild(@javax.annotation.Nonnull Boolean enableBranchAutoBuild) {
    this.enableBranchAutoBuild = enableBranchAutoBuild;
    return this;
  }

  /**
   * Get enableBranchAutoBuild
   * @return enableBranchAutoBuild
   */
  @javax.annotation.Nonnull
  public Boolean getEnableBranchAutoBuild() {
    return enableBranchAutoBuild;
  }

  public void setEnableBranchAutoBuild(@javax.annotation.Nonnull Boolean enableBranchAutoBuild) {
    this.enableBranchAutoBuild = enableBranchAutoBuild;
  }


  public App enableBranchAutoDeletion(@javax.annotation.Nullable Boolean enableBranchAutoDeletion) {
    this.enableBranchAutoDeletion = enableBranchAutoDeletion;
    return this;
  }

  /**
   * Get enableBranchAutoDeletion
   * @return enableBranchAutoDeletion
   */
  @javax.annotation.Nullable
  public Boolean getEnableBranchAutoDeletion() {
    return enableBranchAutoDeletion;
  }

  public void setEnableBranchAutoDeletion(@javax.annotation.Nullable Boolean enableBranchAutoDeletion) {
    this.enableBranchAutoDeletion = enableBranchAutoDeletion;
  }


  public App enableBasicAuth(@javax.annotation.Nonnull Boolean enableBasicAuth) {
    this.enableBasicAuth = enableBasicAuth;
    return this;
  }

  /**
   * Get enableBasicAuth
   * @return enableBasicAuth
   */
  @javax.annotation.Nonnull
  public Boolean getEnableBasicAuth() {
    return enableBasicAuth;
  }

  public void setEnableBasicAuth(@javax.annotation.Nonnull Boolean enableBasicAuth) {
    this.enableBasicAuth = enableBasicAuth;
  }


  public App basicAuthCredentials(@javax.annotation.Nullable String basicAuthCredentials) {
    this.basicAuthCredentials = basicAuthCredentials;
    return this;
  }

  /**
   * Get basicAuthCredentials
   * @return basicAuthCredentials
   */
  @javax.annotation.Nullable
  public String getBasicAuthCredentials() {
    return basicAuthCredentials;
  }

  public void setBasicAuthCredentials(@javax.annotation.Nullable String basicAuthCredentials) {
    this.basicAuthCredentials = basicAuthCredentials;
  }


  public App customRules(@javax.annotation.Nullable List customRules) {
    this.customRules = customRules;
    return this;
  }

  /**
   * Get customRules
   * @return customRules
   */
  @javax.annotation.Nullable
  public List getCustomRules() {
    return customRules;
  }

  public void setCustomRules(@javax.annotation.Nullable List customRules) {
    this.customRules = customRules;
  }


  public App productionBranch(@javax.annotation.Nullable AppProductionBranch productionBranch) {
    this.productionBranch = productionBranch;
    return this;
  }

  /**
   * Get productionBranch
   * @return productionBranch
   */
  @javax.annotation.Nullable
  public AppProductionBranch getProductionBranch() {
    return productionBranch;
  }

  public void setProductionBranch(@javax.annotation.Nullable AppProductionBranch productionBranch) {
    this.productionBranch = productionBranch;
  }


  public App buildSpec(@javax.annotation.Nullable String buildSpec) {
    this.buildSpec = buildSpec;
    return this;
  }

  /**
   * Get buildSpec
   * @return buildSpec
   */
  @javax.annotation.Nullable
  public String getBuildSpec() {
    return buildSpec;
  }

  public void setBuildSpec(@javax.annotation.Nullable String buildSpec) {
    this.buildSpec = buildSpec;
  }


  public App customHeaders(@javax.annotation.Nullable String customHeaders) {
    this.customHeaders = customHeaders;
    return this;
  }

  /**
   * Get customHeaders
   * @return customHeaders
   */
  @javax.annotation.Nullable
  public String getCustomHeaders() {
    return customHeaders;
  }

  public void setCustomHeaders(@javax.annotation.Nullable String customHeaders) {
    this.customHeaders = customHeaders;
  }


  public App enableAutoBranchCreation(@javax.annotation.Nullable Boolean enableAutoBranchCreation) {
    this.enableAutoBranchCreation = enableAutoBranchCreation;
    return this;
  }

  /**
   * Get enableAutoBranchCreation
   * @return enableAutoBranchCreation
   */
  @javax.annotation.Nullable
  public Boolean getEnableAutoBranchCreation() {
    return enableAutoBranchCreation;
  }

  public void setEnableAutoBranchCreation(@javax.annotation.Nullable Boolean enableAutoBranchCreation) {
    this.enableAutoBranchCreation = enableAutoBranchCreation;
  }


  public App autoBranchCreationPatterns(@javax.annotation.Nullable List autoBranchCreationPatterns) {
    this.autoBranchCreationPatterns = autoBranchCreationPatterns;
    return this;
  }

  /**
   * Get autoBranchCreationPatterns
   * @return autoBranchCreationPatterns
   */
  @javax.annotation.Nullable
  public List getAutoBranchCreationPatterns() {
    return autoBranchCreationPatterns;
  }

  public void setAutoBranchCreationPatterns(@javax.annotation.Nullable List autoBranchCreationPatterns) {
    this.autoBranchCreationPatterns = autoBranchCreationPatterns;
  }


  public App autoBranchCreationConfig(@javax.annotation.Nullable AppAutoBranchCreationConfig autoBranchCreationConfig) {
    this.autoBranchCreationConfig = autoBranchCreationConfig;
    return this;
  }

  /**
   * Get autoBranchCreationConfig
   * @return autoBranchCreationConfig
   */
  @javax.annotation.Nullable
  public AppAutoBranchCreationConfig getAutoBranchCreationConfig() {
    return autoBranchCreationConfig;
  }

  public void setAutoBranchCreationConfig(@javax.annotation.Nullable AppAutoBranchCreationConfig autoBranchCreationConfig) {
    this.autoBranchCreationConfig = autoBranchCreationConfig;
  }


  public App repositoryCloneMethod(@javax.annotation.Nullable RepositoryCloneMethod repositoryCloneMethod) {
    this.repositoryCloneMethod = repositoryCloneMethod;
    return this;
  }

  /**
   * Get repositoryCloneMethod
   * @return repositoryCloneMethod
   */
  @javax.annotation.Nullable
  public RepositoryCloneMethod getRepositoryCloneMethod() {
    return repositoryCloneMethod;
  }

  public void setRepositoryCloneMethod(@javax.annotation.Nullable RepositoryCloneMethod repositoryCloneMethod) {
    this.repositoryCloneMethod = repositoryCloneMethod;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    App app = (App) o;
    return Objects.equals(this.appId, app.appId) &&
        Objects.equals(this.appArn, app.appArn) &&
        Objects.equals(this.name, app.name) &&
        Objects.equals(this.tags, app.tags) &&
        Objects.equals(this.description, app.description) &&
        Objects.equals(this.repository, app.repository) &&
        Objects.equals(this.platform, app.platform) &&
        Objects.equals(this.createTime, app.createTime) &&
        Objects.equals(this.updateTime, app.updateTime) &&
        Objects.equals(this.iamServiceRoleArn, app.iamServiceRoleArn) &&
        Objects.equals(this.environmentVariables, app.environmentVariables) &&
        Objects.equals(this.defaultDomain, app.defaultDomain) &&
        Objects.equals(this.enableBranchAutoBuild, app.enableBranchAutoBuild) &&
        Objects.equals(this.enableBranchAutoDeletion, app.enableBranchAutoDeletion) &&
        Objects.equals(this.enableBasicAuth, app.enableBasicAuth) &&
        Objects.equals(this.basicAuthCredentials, app.basicAuthCredentials) &&
        Objects.equals(this.customRules, app.customRules) &&
        Objects.equals(this.productionBranch, app.productionBranch) &&
        Objects.equals(this.buildSpec, app.buildSpec) &&
        Objects.equals(this.customHeaders, app.customHeaders) &&
        Objects.equals(this.enableAutoBranchCreation, app.enableAutoBranchCreation) &&
        Objects.equals(this.autoBranchCreationPatterns, app.autoBranchCreationPatterns) &&
        Objects.equals(this.autoBranchCreationConfig, app.autoBranchCreationConfig) &&
        Objects.equals(this.repositoryCloneMethod, app.repositoryCloneMethod);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appId, appArn, name, tags, description, repository, platform, createTime, updateTime, iamServiceRoleArn, environmentVariables, defaultDomain, enableBranchAutoBuild, enableBranchAutoDeletion, enableBasicAuth, basicAuthCredentials, customRules, productionBranch, buildSpec, customHeaders, enableAutoBranchCreation, autoBranchCreationPatterns, autoBranchCreationConfig, repositoryCloneMethod);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class App {\n");
    sb.append("    appId: ").append(toIndentedString(appId)).append("\n");
    sb.append("    appArn: ").append(toIndentedString(appArn)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    repository: ").append(toIndentedString(repository)).append("\n");
    sb.append("    platform: ").append(toIndentedString(platform)).append("\n");
    sb.append("    createTime: ").append(toIndentedString(createTime)).append("\n");
    sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
    sb.append("    iamServiceRoleArn: ").append(toIndentedString(iamServiceRoleArn)).append("\n");
    sb.append("    environmentVariables: ").append(toIndentedString(environmentVariables)).append("\n");
    sb.append("    defaultDomain: ").append(toIndentedString(defaultDomain)).append("\n");
    sb.append("    enableBranchAutoBuild: ").append(toIndentedString(enableBranchAutoBuild)).append("\n");
    sb.append("    enableBranchAutoDeletion: ").append(toIndentedString(enableBranchAutoDeletion)).append("\n");
    sb.append("    enableBasicAuth: ").append(toIndentedString(enableBasicAuth)).append("\n");
    sb.append("    basicAuthCredentials: ").append(toIndentedString(basicAuthCredentials)).append("\n");
    sb.append("    customRules: ").append(toIndentedString(customRules)).append("\n");
    sb.append("    productionBranch: ").append(toIndentedString(productionBranch)).append("\n");
    sb.append("    buildSpec: ").append(toIndentedString(buildSpec)).append("\n");
    sb.append("    customHeaders: ").append(toIndentedString(customHeaders)).append("\n");
    sb.append("    enableAutoBranchCreation: ").append(toIndentedString(enableAutoBranchCreation)).append("\n");
    sb.append("    autoBranchCreationPatterns: ").append(toIndentedString(autoBranchCreationPatterns)).append("\n");
    sb.append("    autoBranchCreationConfig: ").append(toIndentedString(autoBranchCreationConfig)).append("\n");
    sb.append("    repositoryCloneMethod: ").append(toIndentedString(repositoryCloneMethod)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("appId");
    openapiFields.add("appArn");
    openapiFields.add("name");
    openapiFields.add("tags");
    openapiFields.add("description");
    openapiFields.add("repository");
    openapiFields.add("platform");
    openapiFields.add("createTime");
    openapiFields.add("updateTime");
    openapiFields.add("iamServiceRoleArn");
    openapiFields.add("environmentVariables");
    openapiFields.add("defaultDomain");
    openapiFields.add("enableBranchAutoBuild");
    openapiFields.add("enableBranchAutoDeletion");
    openapiFields.add("enableBasicAuth");
    openapiFields.add("basicAuthCredentials");
    openapiFields.add("customRules");
    openapiFields.add("productionBranch");
    openapiFields.add("buildSpec");
    openapiFields.add("customHeaders");
    openapiFields.add("enableAutoBranchCreation");
    openapiFields.add("autoBranchCreationPatterns");
    openapiFields.add("autoBranchCreationConfig");
    openapiFields.add("repositoryCloneMethod");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("appId");
    openapiRequiredFields.add("appArn");
    openapiRequiredFields.add("name");
    openapiRequiredFields.add("description");
    openapiRequiredFields.add("repository");
    openapiRequiredFields.add("platform");
    openapiRequiredFields.add("createTime");
    openapiRequiredFields.add("updateTime");
    openapiRequiredFields.add("environmentVariables");
    openapiRequiredFields.add("defaultDomain");
    openapiRequiredFields.add("enableBranchAutoBuild");
    openapiRequiredFields.add("enableBasicAuth");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to App
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!App.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in App is not found in the empty JSON string", App.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!App.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `App` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : App.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `appId`
      String.validateJsonElement(jsonObj.get("appId"));
      // validate the required field `appArn`
      String.validateJsonElement(jsonObj.get("appArn"));
      // validate the required field `name`
      String.validateJsonElement(jsonObj.get("name"));
      // validate the optional field `tags`
      if (jsonObj.get("tags") != null && !jsonObj.get("tags").isJsonNull()) {
        Map.validateJsonElement(jsonObj.get("tags"));
      }
      // validate the required field `description`
      String.validateJsonElement(jsonObj.get("description"));
      // validate the required field `repository`
      String.validateJsonElement(jsonObj.get("repository"));
      // validate the required field `platform`
      Platform.validateJsonElement(jsonObj.get("platform"));
      // validate the required field `createTime`
      OffsetDateTime.validateJsonElement(jsonObj.get("createTime"));
      // validate the required field `updateTime`
      OffsetDateTime.validateJsonElement(jsonObj.get("updateTime"));
      // validate the optional field `iamServiceRoleArn`
      if (jsonObj.get("iamServiceRoleArn") != null && !jsonObj.get("iamServiceRoleArn").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("iamServiceRoleArn"));
      }
      // validate the required field `environmentVariables`
      Map.validateJsonElement(jsonObj.get("environmentVariables"));
      // validate the required field `defaultDomain`
      String.validateJsonElement(jsonObj.get("defaultDomain"));
      // validate the required field `enableBranchAutoBuild`
      Boolean.validateJsonElement(jsonObj.get("enableBranchAutoBuild"));
      // validate the optional field `enableBranchAutoDeletion`
      if (jsonObj.get("enableBranchAutoDeletion") != null && !jsonObj.get("enableBranchAutoDeletion").isJsonNull()) {
        Boolean.validateJsonElement(jsonObj.get("enableBranchAutoDeletion"));
      }
      // validate the required field `enableBasicAuth`
      Boolean.validateJsonElement(jsonObj.get("enableBasicAuth"));
      // validate the optional field `basicAuthCredentials`
      if (jsonObj.get("basicAuthCredentials") != null && !jsonObj.get("basicAuthCredentials").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("basicAuthCredentials"));
      }
      // validate the optional field `customRules`
      if (jsonObj.get("customRules") != null && !jsonObj.get("customRules").isJsonNull()) {
        List.validateJsonElement(jsonObj.get("customRules"));
      }
      // validate the optional field `productionBranch`
      if (jsonObj.get("productionBranch") != null && !jsonObj.get("productionBranch").isJsonNull()) {
        AppProductionBranch.validateJsonElement(jsonObj.get("productionBranch"));
      }
      // validate the optional field `buildSpec`
      if (jsonObj.get("buildSpec") != null && !jsonObj.get("buildSpec").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("buildSpec"));
      }
      // validate the optional field `customHeaders`
      if (jsonObj.get("customHeaders") != null && !jsonObj.get("customHeaders").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("customHeaders"));
      }
      // validate the optional field `enableAutoBranchCreation`
      if (jsonObj.get("enableAutoBranchCreation") != null && !jsonObj.get("enableAutoBranchCreation").isJsonNull()) {
        Boolean.validateJsonElement(jsonObj.get("enableAutoBranchCreation"));
      }
      // validate the optional field `autoBranchCreationPatterns`
      if (jsonObj.get("autoBranchCreationPatterns") != null && !jsonObj.get("autoBranchCreationPatterns").isJsonNull()) {
        List.validateJsonElement(jsonObj.get("autoBranchCreationPatterns"));
      }
      // validate the optional field `autoBranchCreationConfig`
      if (jsonObj.get("autoBranchCreationConfig") != null && !jsonObj.get("autoBranchCreationConfig").isJsonNull()) {
        AppAutoBranchCreationConfig.validateJsonElement(jsonObj.get("autoBranchCreationConfig"));
      }
      // validate the optional field `repositoryCloneMethod`
      if (jsonObj.get("repositoryCloneMethod") != null && !jsonObj.get("repositoryCloneMethod").isJsonNull()) {
        RepositoryCloneMethod.validateJsonElement(jsonObj.get("repositoryCloneMethod"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!App.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'App' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<App> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(App.class));

       return (TypeAdapter<T>) new TypeAdapter<App>() {
           @Override
           public void write(JsonWriter out, App value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public App read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of App given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of App
   * @throws IOException if the JSON string is invalid with respect to App
   */
  public static App fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, App.class);
  }

  /**
   * Convert an instance of App to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

