/*
 * AWS Amplify
 * Amplify enables developers to develop and deploy cloud-powered mobile and web apps. The Amplify Console provides a continuous delivery and hosting service for web applications. For more information, see the <a href=\"https://docs.aws.amazon.com/amplify/latest/userguide/welcome.html\">Amplify Console User Guide</a>. The Amplify Framework is a comprehensive set of SDKs, libraries, tools, and documentation for client app development. For more information, see the <a href=\"https://docs.amplify.aws/\">Amplify Framework.</a> 
 *
 * The version of the OpenAPI document: 2017-07-25
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * CreateBackendEnvironmentResultBackendEnvironment
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:08:57.241962+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class CreateBackendEnvironmentResultBackendEnvironment {
  public static final String SERIALIZED_NAME_BACKEND_ENVIRONMENT_ARN = "backendEnvironmentArn";
  @SerializedName(SERIALIZED_NAME_BACKEND_ENVIRONMENT_ARN)
  @javax.annotation.Nonnull
  private String backendEnvironmentArn;

  public static final String SERIALIZED_NAME_ENVIRONMENT_NAME = "environmentName";
  @SerializedName(SERIALIZED_NAME_ENVIRONMENT_NAME)
  @javax.annotation.Nonnull
  private String environmentName;

  public static final String SERIALIZED_NAME_STACK_NAME = "stackName";
  @SerializedName(SERIALIZED_NAME_STACK_NAME)
  @javax.annotation.Nullable
  private String stackName;

  public static final String SERIALIZED_NAME_DEPLOYMENT_ARTIFACTS = "deploymentArtifacts";
  @SerializedName(SERIALIZED_NAME_DEPLOYMENT_ARTIFACTS)
  @javax.annotation.Nullable
  private String deploymentArtifacts;

  public static final String SERIALIZED_NAME_CREATE_TIME = "createTime";
  @SerializedName(SERIALIZED_NAME_CREATE_TIME)
  @javax.annotation.Nonnull
  private OffsetDateTime createTime;

  public static final String SERIALIZED_NAME_UPDATE_TIME = "updateTime";
  @SerializedName(SERIALIZED_NAME_UPDATE_TIME)
  @javax.annotation.Nonnull
  private OffsetDateTime updateTime;

  public CreateBackendEnvironmentResultBackendEnvironment() {
  }

  public CreateBackendEnvironmentResultBackendEnvironment backendEnvironmentArn(@javax.annotation.Nonnull String backendEnvironmentArn) {
    this.backendEnvironmentArn = backendEnvironmentArn;
    return this;
  }

  /**
   * Get backendEnvironmentArn
   * @return backendEnvironmentArn
   */
  @javax.annotation.Nonnull
  public String getBackendEnvironmentArn() {
    return backendEnvironmentArn;
  }

  public void setBackendEnvironmentArn(@javax.annotation.Nonnull String backendEnvironmentArn) {
    this.backendEnvironmentArn = backendEnvironmentArn;
  }


  public CreateBackendEnvironmentResultBackendEnvironment environmentName(@javax.annotation.Nonnull String environmentName) {
    this.environmentName = environmentName;
    return this;
  }

  /**
   * Get environmentName
   * @return environmentName
   */
  @javax.annotation.Nonnull
  public String getEnvironmentName() {
    return environmentName;
  }

  public void setEnvironmentName(@javax.annotation.Nonnull String environmentName) {
    this.environmentName = environmentName;
  }


  public CreateBackendEnvironmentResultBackendEnvironment stackName(@javax.annotation.Nullable String stackName) {
    this.stackName = stackName;
    return this;
  }

  /**
   * Get stackName
   * @return stackName
   */
  @javax.annotation.Nullable
  public String getStackName() {
    return stackName;
  }

  public void setStackName(@javax.annotation.Nullable String stackName) {
    this.stackName = stackName;
  }


  public CreateBackendEnvironmentResultBackendEnvironment deploymentArtifacts(@javax.annotation.Nullable String deploymentArtifacts) {
    this.deploymentArtifacts = deploymentArtifacts;
    return this;
  }

  /**
   * Get deploymentArtifacts
   * @return deploymentArtifacts
   */
  @javax.annotation.Nullable
  public String getDeploymentArtifacts() {
    return deploymentArtifacts;
  }

  public void setDeploymentArtifacts(@javax.annotation.Nullable String deploymentArtifacts) {
    this.deploymentArtifacts = deploymentArtifacts;
  }


  public CreateBackendEnvironmentResultBackendEnvironment createTime(@javax.annotation.Nonnull OffsetDateTime createTime) {
    this.createTime = createTime;
    return this;
  }

  /**
   * Get createTime
   * @return createTime
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getCreateTime() {
    return createTime;
  }

  public void setCreateTime(@javax.annotation.Nonnull OffsetDateTime createTime) {
    this.createTime = createTime;
  }


  public CreateBackendEnvironmentResultBackendEnvironment updateTime(@javax.annotation.Nonnull OffsetDateTime updateTime) {
    this.updateTime = updateTime;
    return this;
  }

  /**
   * Get updateTime
   * @return updateTime
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getUpdateTime() {
    return updateTime;
  }

  public void setUpdateTime(@javax.annotation.Nonnull OffsetDateTime updateTime) {
    this.updateTime = updateTime;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateBackendEnvironmentResultBackendEnvironment createBackendEnvironmentResultBackendEnvironment = (CreateBackendEnvironmentResultBackendEnvironment) o;
    return Objects.equals(this.backendEnvironmentArn, createBackendEnvironmentResultBackendEnvironment.backendEnvironmentArn) &&
        Objects.equals(this.environmentName, createBackendEnvironmentResultBackendEnvironment.environmentName) &&
        Objects.equals(this.stackName, createBackendEnvironmentResultBackendEnvironment.stackName) &&
        Objects.equals(this.deploymentArtifacts, createBackendEnvironmentResultBackendEnvironment.deploymentArtifacts) &&
        Objects.equals(this.createTime, createBackendEnvironmentResultBackendEnvironment.createTime) &&
        Objects.equals(this.updateTime, createBackendEnvironmentResultBackendEnvironment.updateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(backendEnvironmentArn, environmentName, stackName, deploymentArtifacts, createTime, updateTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateBackendEnvironmentResultBackendEnvironment {\n");
    sb.append("    backendEnvironmentArn: ").append(toIndentedString(backendEnvironmentArn)).append("\n");
    sb.append("    environmentName: ").append(toIndentedString(environmentName)).append("\n");
    sb.append("    stackName: ").append(toIndentedString(stackName)).append("\n");
    sb.append("    deploymentArtifacts: ").append(toIndentedString(deploymentArtifacts)).append("\n");
    sb.append("    createTime: ").append(toIndentedString(createTime)).append("\n");
    sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("backendEnvironmentArn");
    openapiFields.add("environmentName");
    openapiFields.add("stackName");
    openapiFields.add("deploymentArtifacts");
    openapiFields.add("createTime");
    openapiFields.add("updateTime");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("backendEnvironmentArn");
    openapiRequiredFields.add("environmentName");
    openapiRequiredFields.add("createTime");
    openapiRequiredFields.add("updateTime");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreateBackendEnvironmentResultBackendEnvironment
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateBackendEnvironmentResultBackendEnvironment.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateBackendEnvironmentResultBackendEnvironment is not found in the empty JSON string", CreateBackendEnvironmentResultBackendEnvironment.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreateBackendEnvironmentResultBackendEnvironment.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CreateBackendEnvironmentResultBackendEnvironment` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CreateBackendEnvironmentResultBackendEnvironment.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `backendEnvironmentArn`
      String.validateJsonElement(jsonObj.get("backendEnvironmentArn"));
      // validate the required field `environmentName`
      String.validateJsonElement(jsonObj.get("environmentName"));
      // validate the optional field `stackName`
      if (jsonObj.get("stackName") != null && !jsonObj.get("stackName").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("stackName"));
      }
      // validate the optional field `deploymentArtifacts`
      if (jsonObj.get("deploymentArtifacts") != null && !jsonObj.get("deploymentArtifacts").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("deploymentArtifacts"));
      }
      // validate the required field `createTime`
      OffsetDateTime.validateJsonElement(jsonObj.get("createTime"));
      // validate the required field `updateTime`
      OffsetDateTime.validateJsonElement(jsonObj.get("updateTime"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateBackendEnvironmentResultBackendEnvironment.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateBackendEnvironmentResultBackendEnvironment' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateBackendEnvironmentResultBackendEnvironment> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateBackendEnvironmentResultBackendEnvironment.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateBackendEnvironmentResultBackendEnvironment>() {
           @Override
           public void write(JsonWriter out, CreateBackendEnvironmentResultBackendEnvironment value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateBackendEnvironmentResultBackendEnvironment read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreateBackendEnvironmentResultBackendEnvironment given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateBackendEnvironmentResultBackendEnvironment
   * @throws IOException if the JSON string is invalid with respect to CreateBackendEnvironmentResultBackendEnvironment
   */
  public static CreateBackendEnvironmentResultBackendEnvironment fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateBackendEnvironmentResultBackendEnvironment.class);
  }

  /**
   * Convert an instance of CreateBackendEnvironmentResultBackendEnvironment to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

