/*
 * AWS Amplify
 * Amplify enables developers to develop and deploy cloud-powered mobile and web apps. The Amplify Console provides a continuous delivery and hosting service for web applications. For more information, see the <a href=\"https://docs.aws.amazon.com/amplify/latest/userguide/welcome.html\">Amplify Console User Guide</a>. The Amplify Framework is a comprehensive set of SDKs, libraries, tools, and documentation for client app development. For more information, see the <a href=\"https://docs.amplify.aws/\">Amplify Framework.</a> 
 *
 * The version of the OpenAPI document: 2017-07-25
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.SubDomainSubDomainSetting;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 *  The subdomain for the domain association. 
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:08:57.241962+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class SubDomain {
  public static final String SERIALIZED_NAME_SUB_DOMAIN_SETTING = "subDomainSetting";
  @SerializedName(SERIALIZED_NAME_SUB_DOMAIN_SETTING)
  @javax.annotation.Nonnull
  private SubDomainSubDomainSetting subDomainSetting;

  public static final String SERIALIZED_NAME_VERIFIED = "verified";
  @SerializedName(SERIALIZED_NAME_VERIFIED)
  @javax.annotation.Nonnull
  private Boolean verified;

  public static final String SERIALIZED_NAME_DNS_RECORD = "dnsRecord";
  @SerializedName(SERIALIZED_NAME_DNS_RECORD)
  @javax.annotation.Nonnull
  private String dnsRecord;

  public SubDomain() {
  }

  public SubDomain subDomainSetting(@javax.annotation.Nonnull SubDomainSubDomainSetting subDomainSetting) {
    this.subDomainSetting = subDomainSetting;
    return this;
  }

  /**
   * Get subDomainSetting
   * @return subDomainSetting
   */
  @javax.annotation.Nonnull
  public SubDomainSubDomainSetting getSubDomainSetting() {
    return subDomainSetting;
  }

  public void setSubDomainSetting(@javax.annotation.Nonnull SubDomainSubDomainSetting subDomainSetting) {
    this.subDomainSetting = subDomainSetting;
  }


  public SubDomain verified(@javax.annotation.Nonnull Boolean verified) {
    this.verified = verified;
    return this;
  }

  /**
   * Get verified
   * @return verified
   */
  @javax.annotation.Nonnull
  public Boolean getVerified() {
    return verified;
  }

  public void setVerified(@javax.annotation.Nonnull Boolean verified) {
    this.verified = verified;
  }


  public SubDomain dnsRecord(@javax.annotation.Nonnull String dnsRecord) {
    this.dnsRecord = dnsRecord;
    return this;
  }

  /**
   * Get dnsRecord
   * @return dnsRecord
   */
  @javax.annotation.Nonnull
  public String getDnsRecord() {
    return dnsRecord;
  }

  public void setDnsRecord(@javax.annotation.Nonnull String dnsRecord) {
    this.dnsRecord = dnsRecord;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubDomain subDomain = (SubDomain) o;
    return Objects.equals(this.subDomainSetting, subDomain.subDomainSetting) &&
        Objects.equals(this.verified, subDomain.verified) &&
        Objects.equals(this.dnsRecord, subDomain.dnsRecord);
  }

  @Override
  public int hashCode() {
    return Objects.hash(subDomainSetting, verified, dnsRecord);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubDomain {\n");
    sb.append("    subDomainSetting: ").append(toIndentedString(subDomainSetting)).append("\n");
    sb.append("    verified: ").append(toIndentedString(verified)).append("\n");
    sb.append("    dnsRecord: ").append(toIndentedString(dnsRecord)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("subDomainSetting");
    openapiFields.add("verified");
    openapiFields.add("dnsRecord");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("subDomainSetting");
    openapiRequiredFields.add("verified");
    openapiRequiredFields.add("dnsRecord");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SubDomain
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SubDomain.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SubDomain is not found in the empty JSON string", SubDomain.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SubDomain.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SubDomain` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SubDomain.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `subDomainSetting`
      SubDomainSubDomainSetting.validateJsonElement(jsonObj.get("subDomainSetting"));
      // validate the required field `verified`
      Boolean.validateJsonElement(jsonObj.get("verified"));
      // validate the required field `dnsRecord`
      String.validateJsonElement(jsonObj.get("dnsRecord"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SubDomain.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SubDomain' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SubDomain> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SubDomain.class));

       return (TypeAdapter<T>) new TypeAdapter<SubDomain>() {
           @Override
           public void write(JsonWriter out, SubDomain value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SubDomain read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SubDomain given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SubDomain
   * @throws IOException if the JSON string is invalid with respect to SubDomain
   */
  public static SubDomain fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SubDomain.class);
  }

  /**
   * Convert an instance of SubDomain to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

